export const exampleObject = {
  name: 'Иван',
  surname: 'Иванов',
  birthday: '07.07.1977',
  work_status: 'Ищу работу',
  email: 'Ivanov777@gmail.com',
  city: 'Семеозерск',
  work_experience_checkbox: false,
  work_period_experience_checkbox: false,
  education_period_checkbox: false,
  qualification_checkbox: false,
  portfolio_checkbox: false,
  education_checkbox: false,
  languages: [
    {
      id: '146664e2-f6c8-4ca0-bc7a-1075afe14fab',
      language: 'Английский',
      level: 'A1',
    },
  ],
  links: [
    {
      id: 'd4917b92-0fc4-463e-8f46-3131d3599024',
      link_name: 'about-me',
      link: 'https://www.youtube.com/watch?v=jfKfPfyJRdk',
    },
  ],
  jobs: [],
  qualifications: [],
  educations: [],
  portfolio: [],
  // img: '../img/example.jpg',
  desired_position: 'Фронтенд',
  level_knowledge: 'Junior',
  phone: '+7(777)777-77-77',
  telegram: 'https://t.me/lucky_men',
  company: 'OOO Эавтоинфоматика"',
  company_website: 'https://avtoinfo.ru',
  current_position: 'менеджер',
  month_work_start: 1,
  year_work_start: '2001',
  month_work_end: 2,
  year_work_end: '2002',
  duties:
    'Провел тщательное исследование пользовательского поведения, что позволило выявить слабые места в интерфейсе. Внес изменения, которые повысили удовлетворенность клиентов на 30% и сократили время выполнения ключевых задач.',
  organization: 'Яндекс',
  course_name: 'веб-разработка',
  work_specialization: 'веб-разработчик',
  month_qual_start: 12,
  year_qual_start: '2022',
  month_qual_end: 9,
  year_qual_end: '2023',
  description_experience: 'Создание проектов и сайтов',
  skills:
    'Я научился проводить глубокий анализ пользовательских потребностей, применять методики Jobs-to-be-Done для более точного понимания целей пользователей. Я успешно интегрировал Figma API для оптимизации рабочих процессов и создал высокоинтерактивные прототипы с использованием Framer X.',
  university_name: 'МГУ',
  year_education_start: '2006',
  year_education_end: '2011',
  university_specialization: 'Менеджмент',
  education_level: 'специалист',
  project_name: 'Место.Россия',
  project_description: 'Сайт посвященный путешествиям по России',
  project_link: 'https://www.youtube.com/watch?v=jfKfPfyJRdk',
  hardskills: ['Лидерство', 'Планирование проекта', 'Управление рисками'],
  about:
    'готовность к релокации в конкретное место (рассматриваю переезд только в города Германии);\nконкретный график (не рассматриваю офис, только гибридный график);\nвыбор конкретной сферы (рассматриваю предложения из Fintech и Edtech);\nограничения по рабочим задачам (не работаю с холодными звонками и продажами);\nчётко показывайте свою мотивацию. Говорите не про выбор направления, а про конкретную должность. Этот пункт особенно актуален для начинающих специалистов.',
  id: '7faa488b-3f0b-47b7-acf4-1021a2487afa',
  resume_name: 'Резюме для Яндекса',
}
